### ISSUE TITLE
将TNT丢入安检门内会使游戏崩溃

### ISSUE THREAD

**Issue by xiaotang27** [DoveCotMC/Metropolis#1]
如题。以下为游戏部分输出内容（其中包括错误日志）。不知道这算不算个bug（（（
```[23:49:53] [Render thread/INFO] (Minecraft) Loaded 2 advancements
[23:51:23] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:24] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:26] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:27] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:31] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:34] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:43] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:47] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:48] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:51:48] [Render thread/INFO] (Minecraft) [STDOUT]: Refreshing dynamic resources
[23:52:57] [Render thread/INFO] (Minecraft) Loaded 3 advancements
[23:53:56] [Server thread/INFO] (Minecraft) Saving and pausing game...
[23:53:56] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[23:53:56] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[23:53:56] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[23:57:23] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
 net.minecraft.util.crash.CrashException: Colliding entity with block
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:879) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.entity.ItemEntity cannot be cast to class net.minecraft.entity.player.PlayerEntity (net.minecraft.entity.ItemEntity and net.minecraft.entity.player.PlayerEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @26aa12dd)
	at team.dovecotmc.metropolis.block.BlockSecurityDoor.onEntityCollision(BlockSecurityDoor.java:56) ~[main/:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock.java:952) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.entity.Entity.checkBlockCollision(Entity.java:1059) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity.java:783) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.entity.Entity.move(Entity.java:752) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.entity.ItemEntity.tick(ItemEntity.java:132) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:712) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.world.World.tickEntity(World.java:466) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:371) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.world.EntityList.forEach(EntityList.java:54) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:339) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875) ~[minecraft-merged-2c60f55561-1.19.2-net.fabricmc.yarn.1_19_2.1.19.2+build.28-v2.jar:?]
	... 5 more
[23:57:23] [Server thread/ERROR] (Minecraft) This crash report has been saved to: C:\Users\zqtan\Downloads\Metropolis-1.19.2-fabric\run\crash-reports\crash-2024-07-21_23.57.23-server.txt
[23:57:23] [Server thread/INFO] (AbstractConnector) Stopped ServerConnector@6aa2a1a9{HTTP/1.1, (http/1.1)}{0.0.0.0:8888}
[23:57:23] [Server thread/INFO] (ContextHandler) Stopped m.l.o.e.j.s.ServletContextHandler@22173fe8{/,jar:file:/C:/Users/zqtan/Downloads/Metropolis-1.19.2-fabric/.gradle/loom-cache/remapped_mods/net_fabricmc_yarn_1_19_2_1_19_2_build_28_v2/maven/modrinth/minecraft-transit-railway/FABRIC-1.19.2-3.2.2-hotfix-1/minecraft-transit-railway-FABRIC-1.19.2-3.2.2-hotfix-1.jar!/assets/mtr/website/,STOPPED}
[23:57:23] [Server thread/INFO] (Minecraft) Stopping server
[23:57:23] [Server thread/INFO] (Minecraft) Saving players
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-21 23:57:23
Description: Colliding entity with block

java.lang.ClassCastException: class net.minecraft.entity.ItemEntity cannot be cast to class net.minecraft.entity.player.PlayerEntity (net.minecraft.entity.ItemEntity and net.minecraft.entity.player.PlayerEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @26aa12dd)
	at team.dovecotmc.metropolis.block.BlockSecurityDoor.onEntityCollision(BlockSecurityDoor.java:56)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock.java:952)
	at net.minecraft.entity.Entity.checkBlockCollision(Entity.java:1059)
	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity.java:783)
	at net.minecraft.entity.Entity.move(Entity.java:752)
	at net.minecraft.entity.ItemEntity.tick(ItemEntity.java:132)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:712)
	at net.minecraft.world.World.tickEntity(World.java:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:371)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:339)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at team.dovecotmc.metropolis.block.BlockSecurityDoor.onEntityCollision(BlockSecurityDoor.java:56)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock.java:952)
	at net.minecraft.entity.Entity.checkBlockCollision(Entity.java:1059)
	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity.java:783)
	at net.minecraft.entity.Entity.move(Entity.java:752)
	at net.minecraft.entity.ItemEntity.tick(ItemEntity.java:132)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:712)
	at net.minecraft.world.World.tickEntity(World.java:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:371)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:339)

-- Block being collided with --
Details:
	Block: Block{metropolis:security_door}[facing=north,half=lower,open=false]
	Block location: World: (9,-60,-59), Section: (at 9,4,5 in 0,-4,-4; chunk contains blocks 0,-64,-64 to 15,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.entity.Entity.checkBlockCollision(Entity.java:1059)
	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity.java:783)
	at net.minecraft.entity.Entity.move(Entity.java:752)
	at net.minecraft.entity.ItemEntity.tick(ItemEntity.java:132)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:712)
	at net.minecraft.world.World.tickEntity(World.java:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:371)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:339)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.ItemEntity)
	Entity ID: 68
	Entity Name: TNT
	Entity's Exact location: 9.50, -59.14, -59.10
	Entity's Block location: World: (9,-60,-60), Section: (at 9,4,4 in 0,-4,-4; chunk contains blocks 0,-64,-64 to 15,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: -0.00, -0.25, 0.14
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity.java:783)
	at net.minecraft.entity.Entity.move(Entity.java:752)
	at net.minecraft.entity.ItemEntity.tick(ItemEntity.java:132)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:712)
	at net.minecraft.world.World.tickEntity(World.java:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:371)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:339)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.ItemEntity)
	Entity ID: 68
	Entity Name: TNT
	Entity's Exact location: 9.50, -59.14, -59.10
	Entity's Block location: World: (9,-60,-60), Section: (at 9,4,4 in 0,-4,-4; chunk contains blocks 0,-64,-64 to 15,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: -0.00, -0.25, 0.14
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.World.tickEntity(World.java:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:371)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:339)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player247'/37, l='ServerLevel[新的世界]', x=9.51, y=-60.00, z=-59.38]]
	Chunk stats: 2856
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 8887 game time, 8887 day time
	Level name: 新的世界
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 86485 (now: false), thunder time: 20154 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:842)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.10, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1134956624 bytes (1082 MiB) / 2558525440 bytes (2440 MiB) up to 8485076992 bytes (8092 MiB)
	CPUs: 22
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) Ultra 9 185H
	Identifier: Intel64 Family 6 Model 170 Stepping 4
	Microarchitecture: unknown
	Frequency (GHz): 3.07
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 22
	Graphics card #0 name: NVIDIA GeForce RTX 4070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2860
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5186
	Graphics card #1 name: Intel(R) Arc(TM) Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 128.00
	Graphics card #1 deviceId: 0x7d55
	Graphics card #1 versionInfo: DriverVersion=31.0.101.5235
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 7.47
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 7.47
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 7.47
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 7.47
	Memory slot #3 type: Unknown
	Memory slot #4 capacity (MB): 4096.00
	Memory slot #4 clockSpeed (GHz): 7.47
	Memory slot #4 type: Unknown
	Memory slot #5 capacity (MB): 4096.00
	Memory slot #5 clockSpeed (GHz): 7.47
	Memory slot #5 type: Unknown
	Memory slot #6 capacity (MB): 4096.00
	Memory slot #6 clockSpeed (GHz): 7.47
	Memory slot #6 type: Unknown
	Memory slot #7 capacity (MB): 4096.00
	Memory slot #7 clockSpeed (GHz): 7.47
	Memory slot #7 type: Unknown
	Virtual memory max (MB): 42597.26
	Virtual memory used (MB): 21272.36
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 131.59
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric-api: Fabric API 0.76.1+1.19.2
		fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
		fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
		fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
		fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
		fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
		fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.1.8+4d0d570390
		fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
		fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
		fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
		fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
		fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
		fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
		fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
		fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
		fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
		fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
		fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.22
		java: Java HotSpot(TM) 64-Bit Server VM 17
		metropolis: Metropolis 1.0.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		mtr: Minecraft Transit Railway 1.19.2-3.2.2-hotfix-1
	Server Running: true
	Player Count: 1 / 8; [ServerPlayerEntity['Player247'/37, l='ServerLevel[新的世界]', x=9.51, y=-60.00, z=-59.38]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: Fabric
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\*****\Downloads\Metropolis-1.19.2-fabric\run\crash-reports\crash-2024-07-21_23.57.23-server.txt```

**Comment by Arrokoth486958** [comment]
已知晓，正在解决

**Comment by Arrokoth486958** [comment]
解决了
https://github.com/DoveCotMC/Metropolis/commit/b670e476afc07ad7a9b15c72c2895687e206c7c7
